version: '2'
services:
  web:
    image: nicopaez/password-api:2.1.0
    expose:
      - "3000"
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
    ports:
      - "8080:8080"

networks:
  default:
    driver: bridge
    name: passwordapi